using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.Json;

namespace AddressGenerator
{
    internal sealed class AddressEntry
    {
        public string Name { get; set; } = string.Empty;
        public string DataType { get; set; } = string.Empty;
        public string Ntsc { get; set; } = string.Empty;
        public string Pal { get; set; } = string.Empty;
        public string Description { get; set; } = string.Empty;
    }

    internal sealed class AddressRoot
    {
        public List<AddressEntry> Addresses { get; set; } = new List<AddressEntry>();
    }

    internal static class Program
    {
        private static int Main(string[] args)
        {
            string inputPath = args.Length > 0 ? args[0] : "data/addresses.json";
            string outputPath = args.Length > 1 ? args[1] : "src/DarkCloud.Memory.Abstractions/Generated/GameAddresses.g.cs";

            if (!File.Exists(inputPath))
            {
                Console.Error.WriteLine($"Input file not found: {inputPath}");
                return 1;
            }

            string json = File.ReadAllText(inputPath);
            AddressRoot? root = JsonSerializer.Deserialize<AddressRoot>(json, new JsonSerializerOptions
            {
                PropertyNameCaseInsensitive = true
            });

            if (root?.Addresses == null || root.Addresses.Count == 0)
            {
                Console.Error.WriteLine("No addresses found in input file.");
                return 1;
            }

            var entries = root.Addresses
                .OrderBy(a => a.Name, StringComparer.Ordinal)
                .ToList();

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("// Generated by AddressGenerator. Do not edit manually.");
            sb.AppendLine();
            sb.AppendLine("using DarkCloud.Memory.Abstractions;");
            sb.AppendLine();
            sb.AppendLine("namespace DarkCloud.Memory.Abstractions.Generated");
            sb.AppendLine("{");
            sb.AppendLine("    /// <summary>");
            sb.AppendLine("    /// Generated game address constants.");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine("    public static class GameAddresses");
            sb.AppendLine("    {");

            foreach (var entry in entries)
            {
                long ntsc = ParseHex(entry.Ntsc);
                string fieldName = ToFieldName(entry.Name);
                sb.AppendLine($"        /// <summary>");
                sb.AppendLine($"        /// {EscapeXml(entry.Description)}");
                sb.AppendLine($"        /// </summary>");
                sb.AppendLine($"        public static readonly GameAddress {fieldName} = new GameAddress(");
                sb.AppendLine($"            \"{entry.Name}\",");
                sb.AppendLine($"            0x{ntsc:X}L,");
                sb.AppendLine($"            \"{entry.DataType}\");");
            }

            sb.AppendLine();
            sb.AppendLine("        /// <summary>");
            sb.AppendLine("        /// All generated addresses in stable order.");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine("        public static readonly System.Collections.Generic.IReadOnlyList<GameAddress> All =");
            sb.AppendLine("            new System.Collections.Generic.List<GameAddress>");
            sb.AppendLine("            {");
            for (int i = 0; i < entries.Count; i++)
            {
                string comma = i < entries.Count - 1 ? "," : string.Empty;
                sb.AppendLine($"                {ToFieldName(entries[i].Name)}{comma}");
            }
            sb.AppendLine("            };");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            string outputDirectory = Path.GetDirectoryName(outputPath) ?? string.Empty;
            if (!string.IsNullOrEmpty(outputDirectory))
                Directory.CreateDirectory(outputDirectory);

            File.WriteAllText(outputPath, sb.ToString(), Encoding.UTF8);
            Console.WriteLine($"Generated {entries.Count} address(es) to {outputPath}");
            return 0;
        }

        private static long ParseHex(string value)
        {
            if (string.IsNullOrWhiteSpace(value))
                throw new ArgumentException("Hex value cannot be empty.");

            string cleaned = value.Trim();
            if (cleaned.StartsWith("0x", StringComparison.OrdinalIgnoreCase))
                cleaned = cleaned.Substring(2);

            if (!long.TryParse(cleaned, System.Globalization.NumberStyles.HexNumber, null, out long result))
                throw new FormatException($"Invalid hexadecimal value: {value}");

            return result;
        }

        private static string ToFieldName(string name)
        {
            if (string.IsNullOrEmpty(name))
                return name;

            // Convert dotted names like Game.BootMarker to Game_BootMarker to be valid C# identifiers.
            return name.Replace('.', '_').Replace(' ', '_').Replace('-', '_');
        }

        private static string EscapeXml(string value)
        {
            if (string.IsNullOrEmpty(value))
                return value;

            return value
                .Replace("&", "&amp;")
                .Replace("<", "&lt;")
                .Replace(">", "&gt;");
        }
    }
}
