<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <RootNamespace>DarkCloudEnhancedMod</RootNamespace>
    <AssemblyName>DarkCloudEnhancedMod</AssemblyName>
    <ApplicationIcon>ModIcon.ico</ApplicationIcon>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <Nullable>disable</Nullable>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
    <GenerateResourceUsePreserializedResources>true</GenerateResourceUsePreserializedResources>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="System" />
    <Reference Include="System.Core" />
    <Reference Include="System.Data" />
    <Reference Include="System.Data.DataSetExtensions" />
    <Reference Include="System.Deployment" />
    <Reference Include="System.Drawing" />
    <Reference Include="System.Net.Http" />
    <Reference Include="System.Windows.Forms" />
    <Reference Include="System.Xml" />
    <Reference Include="System.Xml.Linq" />
    <Reference Include="Microsoft.CSharp" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Resources.Extensions" Version="4.6.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DarkCloud.Memory.Abstractions\DarkCloud.Memory.Abstractions.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <Compile Update="Properties\Resources.Designer.cs">
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
      <DesignTime>True</DesignTime>
    </Compile>
    <EmbeddedResource Update="ModWindow.resx">
      <DependentUpon>ModWindow.cs</DependentUpon>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\RubyMemeFix\Fire" />
    <EmbeddedResource Include="Resources\RubyMemeFix\Holy" />
    <EmbeddedResource Include="Resources\RubyMemeFix\Ice" />
    <EmbeddedResource Include="Resources\RubyMemeFix\Thunder" />
    <EmbeddedResource Include="Resources\RubyMemeFix\Wind" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Resources\PNACH\*.pnach">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\pcsx2_offsetreader.dll" Condition="'$(OS)' == 'Windows_NT'">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <Target Name="CopyFreshPcsx2OffsetReader" AfterTargets="Build" Condition="'$(OS)' == 'Windows_NT'">
    <Copy SourceFiles="$(MSBuildProjectDirectory)/../../native/pcsx2_offsetreader/x64/Release/pcsx2_offsetreader.dll"
          DestinationFiles="$(TargetDir)Resources/pcsx2_offsetreader.dll"
          Condition="Exists('$(MSBuildProjectDirectory)/../../native/pcsx2_offsetreader/x64/Release/pcsx2_offsetreader.dll')" />
  </Target>

</Project>
